baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "scb"

[menu]
  [[menu.main]]
    identifier = "concerts"
    name = "concerts and events"
    url = "/concerts/"
