baseURL = "https://www.swedishcentralband.com"
languageCode = "en-us"
theme = "scb"
title = "Swedish Central Band"
buildFuture = true
[[menu.main]]
identifier = "about"
name = "Om Oss"
url = "/about/"
weight = 1
[[menu.main]]
identifier = "blog"
name = "Nyheter"
url = "/blog/"
weight = 2
[[menu.main]]
identifier = "concerts"
name = "Konserter"
url = "/concerts/"
weight = 3
