---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/concerts
  label: Concerts
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: document
  path: content/about/_index.md
  label: About
- type: document
  path: content/_index.md
  label: Front page
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.48'
